### ISSUE TITLE
Error importing config from stst

### ISSUE THREAD

**Issue by FTAsr** [rgtjf/Semantic-Texual-Similarity-Toolkits#7]
I pip installed stst and tried using it, but get the following error:

>>> import stst
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fa/anaconda/lib/python2.7/site-packages/stst/__init__.py", line 4, in <module>
    from stst.model import *
  File "/Users/fa/anaconda/lib/python2.7/site-packages/stst/model.py", line 6, in <module>
    from stst import config, utils
ImportError: cannot import name config

**Comment by rgtjf** [comment]
Hi, @FTAsr, we have re-organize this repo. Sorry for the inconvenience.
